name: mne
channels:
- defaults
- conda-forge
dependencies:
- python=3.6.1
- pip
- mkl
- numpy
- scipy
- matplotlib
- pyqt
- vtk>=7
- pandas
- scikit-learn
- h5py
- pillow
- statsmodels
- jupyter
- nose
- pytest
- pytest-cov
- sphinx
- joblib
- psutil
- numpydoc
- flake8
- spyder
- pytest-sugar
- pytest-faulthandler
- pydocstyle
- mayavi
- traits
- traitsui
- pyface
- sphinx_bootstrap_theme
- pip:
  - nitime
  - nibabel
  - nilearn
  - pysurfer
  - mne
  - neo
  - git+https://github.com/sphinx-gallery/sphinx-gallery.git
